# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"folder": "07optseq.ipynb",
         "plot_optseq": "07optseq.ipynb",
         "Parameters": "07optseq.ipynb",
         "Mode": "07optseq.ipynb",
         "Activity": "07optseq.ipynb",
         "Resource": "07optseq.ipynb",
         "Temporal": "07optseq.ipynb",
         "State": "07optseq.ipynb",
         "Model": "07optseq.ipynb",
         "make_gannt": "07optseq.ipynb",
         "make_resource_graph": "07optseq.ipynb",
         "ex1": "07optseq.ipynb",
         "ex2": "07optseq.ipynb",
         "ex3": "07optseq.ipynb",
         "ex4": "07optseq.ipynb",
         "ex5": "07optseq.ipynb",
         "ex6": "07optseq.ipynb",
         "ex7": "07optseq.ipynb",
         "ex8": "07optseq.ipynb",
         "ex9": "07optseq.ipynb",
         "ex10": "07optseq.ipynb",
         "ex11": "07optseq.ipynb",
         "ex12": "07optseq.ipynb",
         "ex13": "07optseq.ipynb",
         "ex14": "07optseq.ipynb",
         "ex15": "07optseq.ipynb",
         "ex16": "07optseq.ipynb"}

modules = ["optseq.py"]

doc_url = "https://mikiokubo.github.io/optseqtrial/"

git_url = "https://github.com/mikiokubo/optseqtrial/tree/master/"

def custom_doc_links(name): return None
